version: '2'
services:
    kukulkan-app:
        image: danimaniarqsoft/kukulkan:latest
        depends_on: 
            - kukulkan-mongodb
            - kukulkan-mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://kukulkan-mongodb:27017
            - KUKULKAN_DATA_MYSQL_URI=jdbc:mysql://kukulkan-mysql:3306
        ports:
            - 8080:8080
    kukulkan-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
    kukulkan-mysql:
        image: mysql:5.7.18
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=kukulkan
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
